lib/main.dart, lib/pages/settings_page.dart, lib/pages/store_page.dart
Our first microtransaction! In the store users can buy themes which will show up in the settings theme selection menu. 
Currently there is no currency yet. Once there is we can make the necessary adjustments to factor that into the purchase.
=> Store: buy themes that are added to the settings selection

.gitignore, devtools_options.yaml, lib/auth/auth_util.dart, lib/pages/create_account.dart, lib/pages/login_page.dart, pubspec.lock, pubspec.yaml
Need user log in code so that after successful login, they are directed out of onboard start page
=> Login with auth with onboard start

.gitignore, devtools_options.yaml, lib/auth/auth_util.dart, lib/pages/create_account.dart, lib/pages/login_page.dart, pubspec.lock, pubspec.yaml
The only working account right now is:
Username: javagod123
Password: c++sucks
Very professional test account
=> Work on login screen, but no create account endpoint yet

lib/main.dart, lib/pages/create_account.dart, lib/pages/login_page.dart, pubspec.lock, pubspec.yaml
-password now obscure
-new fields
-new color
-made login look prettier
=> Redoing this pull request because I made login look prettier and accidentally broke the old code:p

lib/auth/requests_util.dart, lib/data/achievements_accessor.dart, lib/data/submit_ride_service.dart, lib/data/user_stats_accessor.dart, lib/data/week_history_accessor.dart, lib/pages/feature_testing.dart
All new buttons output **only to terminal**: nothing changes on phone screen.
To add a new ride, call `SubmitRideService.addRide()` with distance (miles), calories, and time (minutes) information. This automatically updates achievements and user stats.
**JSON parsing still needs implementation.** Otherwise, this function calls the backend endpoint, and in the future, will return a `Map<Integer, AchievementProgress>` mapping achievement ID to a progress class, which stores current progress and a bool taht is true if the achievement has been completed. Achievements are automatically populated as ride info is submitted.
**JSON parsing still needs implementation.** Otherwise, this function calls the backend endpoint, and in the future, will return a `Map<Integer, DayHistory>` mapping a day to …
=> Achievements and Dummy Stats

lib/main.dart, lib/pages/home_page.dart, lib/pages/settings_page.dart, lib/pages/store_page.dart, pubspec.lock
Owned account themes stay the same from one device to another.
If someone could confirm this is working on their device before approving the pull request that would be great. 
Login to account : 
username : braxa2
password : 1234
Pink and teal should be available in the settings, lime should still be purchasable in the store.
=> Refactored Store, Settings, and main AppState to query the backend

.vscode/settings.json, lib/data/user_stats_provider.dart, lib/main.dart, lib/pages/achievements_page.dart
Achievements page connects to backend. Total distance, time, and consistency are displayed. 
Created user_stats_provider.dart which can be imported and used to get access to user stats throughout the app. 
Refactored Achievements page to have more intuitive layout.
=> Refactor achievements

lib/main.dart, lib/pages/achievements_page.dart, lib/pages/home_page.dart, lib/pages/settings_page.dart, pubspec.lock, pubspec.yaml
Username and current streak associated with account show up on home page. 
Account creation date info of the account shows up in settings. 
Small dark mode styling changes.
=> Incorporating user stats

lib/data/purchase_info_accessor.dart, lib/main.dart, lib/pages/rocket_exhaust.dart, lib/pages/rocket_screen.dart, lib/pages/store_page.dart
A rocket boost can be bought for 100 coins in the store. Once bought it opens the rocket_screen where an animated rocket flies from the bottom to the top of the screen. 
Minor changes to the purchase_info_accessor.dart that enable the rocket boost to be bought multiple times. Could be worth looking into a better way to do this later, especially if there are multiple things in the store that can be bought multiple times. Other than that seems to be working well.
=> Rocketboost 

lib/data/achievements_accessor.dart, lib/data/achievements_progress_provider.dart, lib/data/user_stats_provider.dart, lib/main.dart, lib/pages/achievements_page.dart, lib/pages/feature_testing.dart
Implemented achievement progress provider to help access achievement progress throughout the app. Will be used in home_page as well to display achievements the user is working towards. 
Changed feature_testing so we can add rides of differerent values.
=> Achievements Progress specific for user

lib/data/global_leaderboards_accessor.dart, lib/data/user_profile_accessor.dart, lib/data/user_settings_accessor.dart, lib/pages/feature_testing.dart
Sorry for late night ping (though, I'm guessing most of us are still awake 💀)
=> Add user profile, settings, and global leaderboards

lib/data/friend_requests_accessor.dart, lib/data/friends_list_accessor.dart, lib/pages/feature_testing.dart
=> Add friend list and requests, fix time bug(?)

.gitignore, lib/data/achievements_progress_provider.dart, lib/data/friend_requests_accessor.dart, lib/data/friends_list_accessor.dart, lib/data/global_leaderboards_accessor.dart, lib/data/user_profile_accessor.dart, lib/data/user_settings_accessor.dart, lib/data/week_history_provider.dart, lib/main.dart, lib/pages/achievements_page.dart, lib/pages/feature_testing.dart, lib/pages/home_page.dart
=> Update From Main

android/gradle.properties, lib/data/trip_history_provider.dart, lib/main.dart, lib/pages/achievements_page.dart, lib/pages/history_page.dart
Refactored main to a simpler way of having multiple state providers. 
Created the trip history provider file to help change state based on trip history throughout the app. 
Implemented the history page. This includes a trip history summary, all of the trip history organized by day. Individual trips display their respective data. Can filter trips by time, distance, and calories. Can sort to only show trips in a certain range of days.
-- Still need to handle dark mode --
=> History Page Implemented

lib/main.dart, lib/pages/login_page.dart, lib/pages/settings_page.dart
Dark mode and theme connected to the backend. Updates the app state when the user logs in.
=> Dark mode and theme

lib/pages/history_page.dart, lib/pages/settings_page.dart
Added history page dark mode. 
Fixed bug with ride dates not being sorted in the correct order.
=> Implemented History Page Dark Moed

lib/pages/social_page.dart, pubspec.lock
Removing the Accept friend button upon accept/reject
=> Social anxiety

lib/main.dart, lib/pages/home_page.dart, lib/pages/leader_page.dart, lib/pages/login_page.dart, lib/pages/start_page.dart, pubspec.lock
Changed the welcome and login pages appearance. 
App should stay in portrait mode. Leaderboard shows miles instead of km. Made the home page graph cleaner.
=> Various small changes

lib/main.dart, lib/pages/achievements_page.dart, lib/pages/feature_testing.dart, lib/pages/history_page.dart, lib/pages/home_page.dart, lib/pages/social_page.dart, lib/pages/store_page.dart, pubspec.lock, pubspec.yaml
Changed from a left side navigation rail to a bottom navigation bar.
I included feature testing as a fourth option on the navigation bar, we will remove this for the beta version of the app. 
Small changes to home page graph to make better use of the increased screen width.
=> Refactored app navigation

assets/terms_of_service.txt, lib/pages/create_account.dart, lib/pages/settings_page.dart, pubspec.lock, pubspec.yaml
App contributors (credits) can be found in settings. 
Accepting the TOS is now a required step in account creation.
=> Added Credits and Terms of Service

lib/data/user_daily_goal_provider.dart, lib/main.dart, lib/pages/calendar_view.dart, lib/pages/home_page.dart, lib/pages/social_page.dart
Implemented daily goal provider. Home page shows daily goals. Can update goals in profile.
=> Daily goals

lib/pages/social_page.dart
Health information can now be set in the profile tab.
=> Health information

lib/auth/auth_util.dart, lib/pages/feature_testing.dart, lib/pages/start_page.dart, pubspec.lock, pubspec.yaml
I got too lazy to keep logging in, so we do a little trolling
=> Token disk persistence - auto login

lib/pages/routes_page.dart
=> -added durationa nd stuff

ios/Podfile.lock, ios/Runner.xcodeproj/project.pbxproj, lib/pages/social_page.dart, pubspec.lock
=> added friends tab in social page

lib/pages/home_page.dart, lib/pages/packs_page.dart, lib/pages/social_page.dart, pubspec.lock
Team challenges, "Packs", can be accessed through a tab in the social page. Users can create packs and take on various challenges. You can join any pack as long as you have the pack name and password. The pack owner can change the current challenge without disbanding the pack. Once in a pack the team's contributions will be shown in a pie chart.
--- Still need to implement an easy way to add your friends to the pack ---
=> Team challenges packs

lib/main.dart, lib/pages/create_account.dart, lib/pages/history_page.dart, lib/pages/home_page.dart, lib/pages/leader_page.dart, lib/pages/login_page.dart, lib/pages/packs_page.dart, lib/pages/social_page.dart, lib/widgets/notification_scheduler.dart
Several requested changes based on discussion in our team meeting on 4/23.
Major features : 
- invite people to packs by username
- appbar CG logo takes user to home page 
- tutorial can be skipped
Made UI changes to home page and added some simple animations when it builds.
=> Pack invites, appbar nav, tutorial skip

lib/main.dart, lib/pages/achievements_page.dart, lib/pages/home_page.dart, lib/pages/social_page.dart
Shortened tutorial, achievement cards grow on tap, possible fix to showcase problem
=> Small changes

lib/data/notifications_accessor.dart, lib/data/packs_accessor.dart, lib/main.dart, lib/pages/feature_testing.dart, lib/pages/local_notifications.dart, lib/pages/packs_page.dart, lib/widgets/notification_scheduler.dart
Notifications can now be set with a frequency of daily, weekly, or one time. This comes with additional UI changes to the notification manager. 
UI changes to packs. 
Fixed bugs :
- navigation errors
- pack name taken
- creating packs with incomplete parameters
- repeating notifications creating strange behavior (only one instance of a notification with it's exact parameters allowed now)
=> Notification Frequency 

lib/pages/routes_page.dart
Improved the post ride alert UI
=> Post ride alert UI

lib/data/health_info_accessor.dart, lib/pages/routes_page.dart
=> Routes show current ride info: miles, mph, duration, calories

lib/pages/routes_page.dart
- Helmet may output (0, 0) as current location if no location is found
- Helmet may output incorrect data at times; while recording, ignore spikes where location changes more than 50 meters
=> Fix bugs on helmet integration

android/gradle.properties, lib/auth/auth_util.dart, lib/pages/routes_page.dart, lib/pages/settings_page.dart, lib/pages/social_page.dart, pubspec.yaml
History --> Route center on route location
Logout button location + app state reset
=> Complete tasks: center previous route when selected, and put logout button into profile

lib/main.dart, lib/pages/home_page.dart, lib/pages/routes_page.dart, lib/pages/social_page.dart, pubspec.lock, pubspec.yaml
When a distance, time, or calorie goal is complete play an animation around the card and a short vibration during live route tracking. 
Updated app state to track if goals are met so they are indicated properly when offline.
=> Route track goal complete

lib/pages/social_page.dart
=> -better fix

lib/pages/ble.dart, lib/pages/packs_page.dart, lib/pages/routes_autofill.dart
Packs UI, routes search bar, scan helmet menu close button
=> UI changes
